TRUNCATE TABLE ONLY financiero.conteo RESTART IDENTITY CASCADE;
TRUNCATE TABLE ONLY financiero.venta_credito RESTART IDENTITY CASCADE;
TRUNCATE TABLE ONLY operaciones.cobro RESTART IDENTITY CASCADE;
TRUNCATE TABLE ONLY operaciones.inventario RESTART IDENTITY CASCADE;
TRUNCATE TABLE ONLY operaciones.movimiento_stock RESTART IDENTITY CASCADE;
TRUNCATE TABLE ONLY operaciones.transferencia RESTART IDENTITY CASCADE;
