export enum TipoMovimiento {
    COMPRA = 'COMPRA',
	VENTA = 'VENTA',
	DEVOLUCION = 'DEVOLUCION',
	DESCARTE= 'DESCARTE',
	AJUSTE = 'AJUSTE',
	TRANSFERENCIA = 'TRANSFERENCIA',
	CALCULO = 'CALCULO',
	ENTRADA = 'ENTRADA',
	SALIDA = 'SALIDA'
}