export enum NecesidadEstado {
  ACTIVO,
  MODIFICADO,
  CANCELADO,
  EN_VERIFICACION,
  EN_VERIFICACION_SOLICITUD_AUTORIZACION,
  VERFICADO_SIN_MODIFICACION,
  VERFICADO_CON_MODIFICACION,
  CONCLUIDO
}
