export enum ROLES {
    VENTA_TOUCH = "VENTA TOUCH",
    CANCELACION_VENTA =  "CANCELACION DE VENTA",
    VER_INVENTARIO =  "VER INVENTARIO",
    CREAR_INVENTARIO =  "CREAR INVENTARIO",
    PARTICIPAR_INVENTARIO =  "PARTICIPAR INVENTARIO"
}