export enum NotaRecepcionEstado {
    PENDIENTE_CONCILIACION = 'PENDIENTE_CONCILIACION',
    CONCILIADA = 'CONCILIADA',
    EN_RECEPCION = 'EN_RECEPCION',
    RECEPCION_PARCIAL = 'RECEPCION_PARCIAL',
    RECEPCION_COMPLETA = 'RECEPCION_COMPLETA',
    CERRADA = 'CERRADA'
} 