export enum TipoBoleta {
  LEGAL,
  COMUN,
}

export enum CompraEstado {
  ACTIVO = 'ACTIVO',
  CANCELADO = 'CANCELADO',
  DEVOLVIDO = 'DEVOLVIDO',
  EN_OBSERVACION = 'EN_OBSERVACION',
  IRREGULAR = 'IRREGULAR',
  PRE_COMPRA = 'PRE_COMPRA',
}

export enum CompraItemEstado {
  SIN_MODIFICACIONN = 'SIN_MODIFICACION',
  MODIFICADO = 'MODIFICADO'
}
