export enum DeliveryEstado {
    ABIERTO = 'ABIERTO', 
    EN_CAMINO = 'EN_CAMINO', 
    ENTREGADO = 'ENTREGADO', 
    CANCELADO = 'CANCELADO', 
    DEVOLVIDO ='DEVOLVIDO',
    PARA_ENTREGA = 'PARA_ENTREGA'
}