export enum TipoArchivoEnte {
  CONTRATO_COMPRA = 'CONTRATO_COMPRA',
  CONTRATO_ALQUILER = 'CONTRATO_ALQUILER',
  CONTRATO_COMODATO = 'CONTRATO_COMODATO',
  FOTO_ESTADO_INICIAL = 'FOTO_ESTADO_INICIAL',
  DOCUMENTO_TRANSFERENCIA = 'DOCUMENTO_TRANSFERENCIA',
  FACTURA = 'FACTURA',
  OTRO = 'OTRO',
}
