export enum PedidoEstado {
  ABIERTO = 'ABIERTO',
  ACTIVO = 'ACTIVO',
  MODIFICADO = 'MODIFICADO',
  CANCELADO = 'CANCELADO',
  REPROGRAMADO = 'REPROGRAMADO',
  EN_VERIFICACION = 'EN_VERIFICACION',
  EN_RECEPCION_NOTA = 'EN_RECEPCION_NOTA',
  EN_RECEPCION_MERCADERIA = 'EN_RECEPCION_MERCADERIA',
  EN_VERIFICACION_SOLICITUD_AUTORIZACION = 'EN_VERIFICACION_SOLICITUD_AUTORIZACION',
  VERFICADO_SIN_MODIFICACION = 'VERFICADO_SIN_MODIFICACION',
  VERFICADO_CON_MODIFICACION = 'VERFICADO_CON_MODIFICACION',
  CONCLUIDO = 'CONCLUIDO'
}

export enum PedidoItemEstado {
  ACTIVO = 'ACTIVO',
  CANCELADO = 'CANCELADO',
  DEVOLUCION = 'DEVOLUCION',
  CONCLUIDO = 'CONCLUIDO',
  EN_FALTA = 'EN_FALTA'
}
