queue: filial.1
queue-reply-to: filial.1.reply.to
sucursal-id: 1
server-url: http://localhost:8082
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: franco
    password: franco
    virtual-host: bodega
  multirabbitmq:
    enabled: true
    connections:
      servidor:
        host: 172.25.1.200
        port: 5672
        username: franco
        password: franco
        virtual-host: bodega